
// Generated by Selenium IDE
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
public class CelciusFahrenheitTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void celciusFahrenheit() {
    driver.get("http://localhost:8000/modulo01/index.html");
    driver.manage().window().setSize(new Dimension(584, 692));
    driver.findElement(By.id("tipo-conversao")).click();
    {
      WebElement dropdown = driver.findElement(By.id("tipo-conversao"));
      dropdown.findElement(By.xpath("//option[. = 'Celsius para Fahrenheit']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.id("valor")).click();
    driver.findElement(By.id("valor")).sendKeys("100");
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.cssSelector("p:nth-child(2)")).click();
    driver.findElement(By.cssSelector("p:nth-child(3)")).click();
    driver.findElement(By.cssSelector("p:nth-child(3)")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(3)")).getText(), is("Valor convertido: 212"));
    driver.findElement(By.cssSelector("p:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(2)")).getText(), is("Valor original: 100.0"));
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.getTitle(), is("Resultado da Conversão"));
  }
}
