// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FahrenheitCelciusTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void fahrenheitCelcius() {
    driver.get("http://localhost:8000/modulo01/index.html");
    driver.manage().window().setSize(new Dimension(584, 692));
    driver.findElement(By.id("tipo-conversao")).click();
    driver.findElement(By.cssSelector("option:nth-child(1)")).click();
    driver.findElement(By.id("valor")).click();
    driver.findElement(By.id("valor")).sendKeys("212");
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.getTitle(), is("Resultado da Conversão"));
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(2)")).getText(), is("Valor original: 212.0"));
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(3)")).getText(), is("Valor convertido: 100"));
  }
}
